BOARD_USES_WACOMINPUT := true

#BOARD_USES_GENERIC_AUDIO := false
BOARD_USES_ALSA_AUDIO := true
BUILD_WITH_ALSA_UTILS := true

USE_CAMERA_STUB := false
#BOARD_CAMERA_LIBRARIES := libcamera
#BOARD_USES_OLD_CAMERA_HACK := true

#BUILD_WITH_MPLAYER := true
TARGET_HAS_THIRD_PARTY_APPS := true
BOARD_GPU_DRIVERS := i915
BOARD_USES_KBDSENSOR := false
BOARD_USES_HDAPS_ACCEL := true
#TARGET_CPU_SMP := false
BOARD_KERNEL_CMDLINE := root=/dev/ram0 quiet androidboot.hardware=$(TARGET_PRODUCT) video=1024x768 i915.lvds_downclock=1 i915.powersave=1 usbcore.autosuspend=2
WPA_SUPPLICANT_VERSION := VER_0_6_X
BOARD_WPA_SUPPLICANT_DRIVER := AWEXT
BOARD_WPA_SUPPLICANT_PRIVATE_LIB := 

include $(GENERIC_X86_CONFIG_MK)

#BOARD_KERNEL_CMDLINE += SDCARD=sdc
